import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return (
    <>
      <div className="root-layout">THIS IS MY BACKEND</div>
      <div>
        <a href="http://localhost:3000/register">Register</a>
      </div>
    </>
  );
}
